SET NAMES utf8;
SET CHARACTER SET utf8;
DROP TABLE IF EXISTS `#__geoiofertas`;
DROP TABLE IF EXISTS `#__geoiconf`;
DROP TABLE IF EXISTS `#__geoipol1`;
DROP TABLE IF EXISTS `#__geoipol2`;
DROP TABLE IF EXISTS `#__geoipol3`;
DROP TABLE IF EXISTS `#__geoipol4`;
DROP TABLE IF EXISTS `#__geoipol5`;
DROP TABLE IF EXISTS `#__geoipol6`;
DROP TABLE IF EXISTS `#__geoipol7`;
DROP TABLE IF EXISTS `#__geoipol8`;
DROP TABLE IF EXISTS `#__geoipol9`;
DROP TABLE IF EXISTS `#__geoipol10`;
DROP TABLE IF EXISTS `#__geoipol11`;
DROP TABLE IF EXISTS `#_geoiopol1`;
DROP TABLE IF EXISTS `#_geoiopol2`;
DROP TABLE IF EXISTS `#_geoiopol3`;
DROP TABLE IF EXISTS `#_geoiopol4`;
DROP TABLE IF EXISTS `#_geoiopol5`;
DROP TABLE IF EXISTS `#_geoiopol6`;
 
CREATE TABLE `#__geoiofertas` (
  oid int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  geom GEOMETRY NOT NULL,
  TYPEP CHAR(15) NOT NULL,
  TYPEO CHAR(15) NOT NULL,
  VALUE int(15) NOT NULL,
  AREA REAL(10,6),
  ROOMS int(3),
  AGE int(3),
  TOILET int(11),
  TEL1 int(12),
  TEL2 int(12),
  EMAIL CHAR(70) NOT NULL,
  USERNAME CHAR(15) NOT NULL,
  USERID int(9) NOT NULL 
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE `#__geoiofertas` ADD FOREIGN KEY (USERID) REFERENCES #___users(id);
ALTER TABLE `#__geoiofertas` ADD INDEX ( oid ); 
ALTER TABLE `#__geoiofertas` ADD INDEX ( USERID ); 
ALTER TABLE `#__geoiofertas` ADD SPATIAL INDEX ( geom );

CREATE TABLE `#__geoiconf` (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PARAM CHAR(20) NOT NULL,
  VAL CHAR(80) NOT NULL 
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


