DROP TABLE IF EXISTS GeoIOfertas;
DROP TABLE IF EXISTS GeoIConf;
DROP TABLE IF EXISTS GeoIPOL1;
DROP TABLE IF EXISTS GeoIPOL2;
DROP TABLE IF EXISTS GeoIPOL3;
DROP TABLE IF EXISTS GeoIPOL4;
DROP TABLE IF EXISTS GeoIPOL5;
DROP TABLE IF EXISTS GeoIPOL6;
DROP TABLE IF EXISTS GeoIPOL7;
DROP TABLE IF EXISTS GeoIPOL8;
DROP TABLE IF EXISTS GeoIPOL9;
DROP TABLE IF EXISTS GeoIPOL10;
DROP TABLE IF EXISTS GeoIPOL11;
 
CREATE TABLE GeoIOfertas (
  oid int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  geom GEOMETRY NOT NULL,
  TIPOI CHAR(15) NOT NULL,
  TIPOO CHAR(15) NOT NULL,
  PRECIO int(15) NOT NULL,
  AREA REAL(10,6),
  HAB int(3),
  EDAD int(3),
  TOILET int(11),
  TEL1 int(12),
  TEL2 int(12),
  EMAIL CHAR(70) NOT NULL,
  USERNAME CHAR(15) NOT NULL,
  USERID int(9) NOT NULL 
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE GeoIOfertas ADD FOREIGN KEY (USERID) REFERENCES #__users(id);
ALTER TABLE GeoIOfertas ADD INDEX ( oid ); 
ALTER TABLE GeoIOfertas ADD INDEX ( USERID ); 
ALTER TABLE GeoIOfertas ADD SPATIAL INDEX ( geom );

DROP TABLE IF EXISTS GeoIConf;
 
CREATE TABLE GeoIConf (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PARAM CHAR(15) NOT NULL,
  VAL CHAR(30) NOT NULL 
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

INSERT INTO GeoIConf (PARAM , VAL) 
	VALUES 	('EPSG','3857') , 
			('NUMPOL','0'),
			('N_TIPOI','Tipo de Inmueble'),
			('N_TIPOO','Tipo de Oferta'),
			('N_PRECIO','Precio'),
			('N_AREA','Área'),
			('N_HAB','Número de Habitaciones'),
			('N_EDAD','Edad del Inmueble'),
			('N_TOILET','Número de baños'),
			('N_TEL1','Telefono 1'),
			('N_TEL2','Telefono 2'),
			('N_EMAIL','E-mail'),
			('N_USERNAME','Nombre de Usuario');
 
